@startuml
' アプリケーションライフサイクル アクティビティ図

title 画面遷移ライフサイクル

start
:画面初期化;

:画面表示準備;

:画面表示・操作開始;

:表示完了後の初期処理;

:ユーザー操作;

:一時停止;

:完全非表示;

if (再開する?) then (yes)
  :非表示からの再開;
  :画面表示準備;
  :画面表示・操作開始;
else (no)
  :画面破棄;
endif

stop
@enduml 